### ISSUE TITLE
Visit /admin and not redirecting

### ISSUE THREAD

**Issue by loongmxbt** [rwatts3/example-blog-v1.0-beta#2]
Direct visit to /admin shows a 404, I think it's better to do it like old example-blog to have a redirect logic login or not. Is it removed out of core in v1.0?

**Comment by rwatts3** [comment]
Need to go to `/admin/dictionary` or `/login`

**Comment by rwatts3** [comment]
@loongmxbt Did you ever get it working ? . 

If you take a look at the `packages` directory and look at the the templates for `simple-theme` you now have the ability to extend these templates and style your admin panel any way you'd like.

**Comment by loongmxbt** [comment]
Yeah, I can use `/admin/dictionary` to get into admin panel. What I mean is that when I visit `/admin` instead of  `/admin/dictionary`, is it better to check isLogin and redirect to `/admin/dictionary`, or if user doesn't login and visit `/admin`, it will redirect to login page. 

Another problem is when I've already logged in, I visit `/login`, it doesn't go to the admin panel. Anyway, thanks for your help!

**Comment by rwatts3** [comment]
Alright I see, By the way I have created a <gitter.im> chat room for this repository. I am in the room on a daily so feel free to drop in and add questions I may get to them quicker there. 

[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/rwatts3/example-blog-v1.0-beta?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by loongmxbt** [comment]
Yeah, I've seen your previous talk, I'll join the chat when I have other questions.
